

class TestingConfig:
    DEBUG = True
    TESTING = True
    SQLALCHEMY_DATABASE_URI = 'sqlite:///testdatabase.db'
    SECRET_KEY = 'DSFKJHKJH090912'
    JWT_SECRET_KEY = 'IDONTCARE@#HAHAH'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    PRESERVE_CONTEXT_ON_EXCEPTION = False


    